### ISSUE TITLE
Migrate settings from GlobalVars.py to config files

### ISSUE THREAD

**Issue by MatthewCox** [MatthewCox/PyMoronBot#13]
- [x] Configs per server
- [x] Import other config files
- [x] Merge lists/dicts when importing
- [ ] Make all but the '--config' cmdline arg optional

**Comment by HubbeKing** [comment]
You also have a lot of data already in your shelve dataStore. You could easily store the admin list in there, and if need be even separate them per-server.

**Comment by Heufneutje** [comment]
:+1: 

PyHeufyBot stores them in its config file, but having a list you can actually modify at runtime might be even nicer since you don't have to rehash the config file every time you make a change to it.

**Comment by MatthewCox** [comment]
Mostly done, but need to rework how the bot is created to get rid of the required --server cmdline arg
